### ISSUE TITLE
Error during dispatch

### ISSUE THREAD

**Issue by kozo2** [cytoscape/cytoscape-impl#5]
Could you determine the reason for the following error?
I would like to maintain Cytoscape homebrew distribution.
## How to reproduce the error
- Mac OSX 10.11.3
- Java SE 1.8.0_74

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install homebrew/science/cytoscape
cytoscape
```
## The error

```
Cytoscape 3.3.0> ERROR: Bundle org.cytoscape.app-impl [87] EventDispatcher: Error during dispatch. (java.lang.IllegalArgumentException: Parameter 'directory' is not a directory)
java.lang.IllegalArgumentException: Parameter 'directory' is not a directory
    at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:460)
    at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:546)
    at org.cytoscape.app.internal.manager.AppManager.obtainAppsFromDirectory(AppManager.java:1079)
    at org.cytoscape.app.internal.manager.AppManager.initializeApps(AppManager.java:238)
    at org.cytoscape.app.internal.manager.AppManager.attemptInitialization(AppManager.java:230)
    at org.cytoscape.app.internal.manager.AppManager.frameworkEvent(AppManager.java:222)
    at org.apache.felix.framework.util.EventDispatcher.invokeFrameworkListenerCallback(EventDispatcher.java:835)
    at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:785)
    at org.apache.felix.framework.util.EventDispatcher.run(EventDispatcher.java:1088)
    at org.apache.felix.framework.util.EventDispatcher.access$000(EventDispatcher.java:54)
    at org.apache.felix.framework.util.EventDispatcher$1.run(EventDispatcher.java:101)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by kozo2** [comment]
This error does not occur for [the official archive distribution](http://chianti.ucsd.edu/cytoscape-3.3.0/cytoscape-3.3.0.tar.gz).

```
wget http://chianti.ucsd.edu/cytoscape-3.3.0/cytoscape-3.3.0.tar.gz
tar xf cytoscape-3.3.0.tar.gz
bash cytoscape-unix-3.3.0/cytoscape.sh
```
